AppointmentApp/Models/PatientInfo.cs
using System;
namespace AppointmentApp.Models
{
    public class PatientInfo
    {

        public string id { get; set; }


        public string firstName { get; set; }


        public string lastName { get; set; }


        public string emailId { get; set; }


        public string password { get; set; }
    }
}

AppointmentApp/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppointmentApp.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }
    }
}

AppointmentApp/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business;
using Models;
namespace AppointmentApp.Controllers
{
    public class AboutUsController : Controller
    {
        public ActionResult Index()
        {
            var test = PatientProfile.getPatientProfile("jack@gmail.com","jack1234");

            return View ();
        }

        [HttpPost]
        public ActionResult Index(PatientInfo patient)
        {

            string emailId = patient.emailId;
            string password = patient.password;

            var test = PatientProfile.getPatientProfile(emailId, password);

            return View();
        }
    }
}

AppointmentApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;

namespace AppointmentApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var mvcName = typeof(Controller).Assembly.GetName();
            var isMono = Type.GetType("Mono.Runtime") != null;

            ViewData["Version"] = mvcName.Version.Major + "." + mvcName.Version.Minor;
            ViewData["Runtime"] = isMono ? "Mono" : ".NET";

            return View();
        }
    }
}

AppointmentApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using Business;
namespace AppointmentApp.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }

        [HttpPost]
        public ActionResult Index(PatientInfo patient)
        {
            var patientProfileList = new List<PatientInfo>();
            string emailId = patient.emailId;
            string password = patient.password;

            patientProfileList = PatientProfile.getPatientProfile(emailId, password);

            if(patientProfileList != null && patientProfileList.Count > 0) {
                return View("Success");
            } else {
                return View("Failure");
            }
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Failure()
        {
            return View();
        }
    }
}

AppointmentApp/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppointmentApp.Controllers
{
    public class ServicesController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }
    }
}

AppointmentApp/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using Business;

namespace AppointmentApp.Controllers
{
    public class SignUpController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }

        [HttpPost]
        public ActionResult Index(PatientInfo patient)
        {
            string firstName = patient.firstName;
            string lastName = patient.lastName;
            string emailId = patient.emailId;
            string password = patient.password;

            var test = PatientProfile.createPatientProfile(firstName, lastName, emailId , password);

            return View();
        }
    }
}

AppointmentApp/Views/About/index.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
    <link href="../../../Content/main.css" rel="stylesheet" type="text/css" />
    <link href="../../../Content/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                @*<h1><a href="#">Medical Appointment</a></h1>*@
            </div>
            <div id="menu">
                <ul>
                    <li><a href="/" accesskey="1" title="">Homepage</a></li>
                    <li><a href="/services" accesskey="2" title="">Services</a></li>
                    <li class="active"><a href="/about" accesskey="3" title="">About Us</a></li>
                    <li><a href="#" accesskey="5" title="">Contact Us</a></li>
                </ul>
            </div>
        </div>
        <div id="banner" class="container">
            <div class="title">
                <h2>Ayurveda Hospital</h2>
                @*<span class="byline">Make an appointment</span>*@
            </div>
            <ul class="actions">
                <li><a href="#" class="button">Make an appointment</a></li>
            </ul>
        </div>
    </div>
</body>
</html>

AppointmentApp/Views/AboutUs/Index.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
    <link href="../../../Content/main.css" rel="stylesheet" type="text/css" />
    <link href="../../../Content/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="black-header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                <h1><a href="/">Central Perk</a></h1>
            </div>
            <div id="menu">
                <ul>
                    <li><a href="/" accesskey="1" title="">Homepage</a></li>
                    <li><a href="/services" accesskey="2" title="">Services</a></li>
                    <li class="active"><a href="/aboutus" accesskey="3" title="">About Us</a></liclass="active">
                    <li><a href="#" accesskey="5" title="">Contact Us</a></li>
                </ul>
            </div>
        </div>
        <div id="banner" class="container">
            <h1 class="form-heading">login Form</h1>
            <div class="login-form">
                <div class="main-div">
                    <div class="panel">
                        <h2>Admin Login</h2>
                        <p>Please enter your email and password</p>
                    </div>
                    <form id="Login">
                        <div class="form-group">
                            <input type="email" class="form-control" id="inputEmail" placeholder="Email Address" />
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="inputPassword" placeholder="Password" />
                        </div>
                        <div class="forgot">
                            <a href="reset.html">Forgot password?</a>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

AppointmentApp/Views/Home/Index.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
    <link href="../../../Content/main.css" rel="stylesheet" type="text/css" />
    <link href="../../../Content/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="home-header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                @*<h1><a href="#">Medical Appointment</a></h1>*@
            </div>
            <div id="menu">
                <ul>
                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Login/SignUp", "Index", "Login")</li>
                    <li>@Html.ActionLink("About Us", "Index", "AboutUs")</li>
                    <li>@Html.ActionLink("Contact Us", "Index", "Services")</li>
                </ul>
            </div>
        </div>
        <div id="banner" class="container">
            <div class="title">
                <h2>Central Perk Hospital</h2>
                @*<span class="byline">Make an appointment</span>*@
            </div>
            <ul class="actions">
                <li><a href="#" class="button">Make an appointment</a></li>
            </ul>
        </div>
    </div>
</body>
</html>

AppointmentApp/Views/Login/Failure.cshtml
@model AppointmentApp.Models.PatientInfo
@{
    Layout = null;
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
    <link href="../../../Content/main.css" rel="stylesheet" type="text/css" />
    <link href="../../../Content/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="black-header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                <h1><a href="/">Central Perk</a></h1>
            </div>
            <div id="menu">
                <ul>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Login/SignUp", "Index", "Login")</li>
                    <li>@Html.ActionLink("About Us", "Index", "AboutUs")</li>
                    <li>@Html.ActionLink("Contact Us", "Index", "Services")</li>
                </ul>
            </div>
        </div>
        @using (Html.BeginForm("Index", "Login", FormMethod.Post))
        {
            <div id="banner" class="container">
                <h1 class="form-heading">login Form</h1>
                <div class="login-form">
                    <div class="main-div">
                        <div class="panel">
                            <p>Please enter your email and password</p>
                        </div>

                        <div class="form-group red_border">
                            @Html.TextBoxFor(m => m.emailId)
                        </div>
                        <div class="form-group red_border">
                            @Html.TextBoxFor(m => m.password)
                        </div>
                        <div class="forgot">
                            @Html.ActionLink("Create Account?", "Index", "SignUp")
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</body>
</html>

AppointmentApp/Views/Login/Index.cshtml
@model AppointmentApp.Models.PatientInfo
@{
    Layout = null;
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
    <link href="../../../Content/main.css" rel="stylesheet" type="text/css" />
    <link href="../../../Content/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>

    <div id="black-header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                <h1><a href="/">Central Perk</a></h1>
            </div>
            <div id="menu">
                <ul>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Login/SignUp", "Index", "Login")</li>
                    <li>@Html.ActionLink("About Us", "Index", "AboutUs")</li>
                    <li>@Html.ActionLink("Contact Us", "Index", "Services")</li>
                </ul>
            </div>
        </div>
        @using (Html.BeginForm("Index", "Login", FormMethod.Post))
        {
        <div id="banner" class="container">
            <h1 class="form-heading">login Form</h1>
            <div class="login-form">
                <div class="main-div">
                    <div class="panel">

                        <p>Please enter your email and password</p>
                    </div>


                    <div class="form-group">
                        @Html.TextBoxFor(m => m.emailId)
                    </div>
                    <div class="form-group">
                        @Html.TextBoxFor(m => m.password)

                    </div>
                    <div class="forgot">
                        @Html.ActionLink("Create Account?", "Index", "SignUp")
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </div>
            </div>
         </div>
         }

        </div>
</body>
</html>

AppointmentApp/Views/Login/Success.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
    <link href="../../../Content/main.css" rel="stylesheet" type="text/css" />
    <link href="../../../Content/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="black-header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                <h1><a href="/">Central Perk</a></h1>
            </div>
            <div id="menu">
                <ul>
                    <li><a href="/" accesskey="1" title="">Homepage</a></li>
                    <li class="active"><a href="/services" accesskey="2" title="">Services</a></li>
                    <li><a href="/aboutus" accesskey="3" title="">About Us</a></li>
                    <li><a href="#" accesskey="5" title="">Contact Us</a></li>
                </ul>
            </div>
        </div>
        <div id="banner" class="container">
            <div class="title">
                <h3>Convenient Care and Quick, Accurate Lab Results</h3>
                </br>
                <h4>Central Perk provides fast and accurate high-quality lab services in their main hospital and at three convenient locations in the community.</h4>
                </br>
                </br>
                <h3>Laboratory Services at Central Perk Hospital</h3>
                </br>
                <h4>The laboratory at Central Perk Hospital provides high-quality care and quick, accurate results to help physicians diagnose and treat patients effectively. At the Central Perk laboratory, our expert staff supports hospitalized patients as well as those in need of emergency care. We also offer a wide range of outpatient services. In addition to the laboratory on the first floor of Central Perk, you can visit one of our three convenient collection sites throughout the community.</h4>
                <h3>Requesting Laboratory Test Results</h3>
                </br>
                <h4>ou can request a copy of your results at the time of collection by signing a waiver form and providing a photo ID. To protect your privacy, you are the only one who can request your results. We cannot give results over the phone. Read more about our privacy policy.</h4>
            </div>
        </div>
    </div>
</body>
</html>

AppointmentApp/Views/Services/Index.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
    <link href="../../../Content/main.css" rel="stylesheet" type="text/css" />
    <link href="../../../Content/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="black-header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                <h1><a href="/">Central Perk</a></h1>
            </div>
            <div id="menu">
                <ul>
                    <li><a href="/" accesskey="1" title="">Homepage</a></li>
                    <li class="active"><a href="/services" accesskey="2" title="">Services</a></li>
                    <li><a href="/aboutus" accesskey="3" title="">About Us</a></li>
                    <li><a href="#" accesskey="5" title="">Contact Us</a></li>
                </ul>
            </div>
        </div>
        <div id="banner" class="container">
            <div class="title">
                <h3>Convenient Care and Quick, Accurate Lab Results</h3>
                </br>
                <h4>Central Perk provides fast and accurate high-quality lab services in their main hospital and at three convenient locations in the community.</h4>
                </br>
                </br>
                <h3>Laboratory Services at Central Perk Hospital</h3>
                </br>
                <h4>The laboratory at Central Perk Hospital provides high-quality care and quick, accurate results to help physicians diagnose and treat patients effectively. At the Central Perk laboratory, our expert staff supports hospitalized patients as well as those in need of emergency care. We also offer a wide range of outpatient services. In addition to the laboratory on the first floor of Central Perk, you can visit one of our three convenient collection sites throughout the community.</h4>
                <h3>Requesting Laboratory Test Results</h3>
                </br>
                <h4>ou can request a copy of your results at the time of collection by signing a waiver form and providing a photo ID. To protect your privacy, you are the only one who can request your results. We cannot give results over the phone. Read more about our privacy policy.</h4>
            </div>
        </div>
    </div>
</body>
</html>

AppointmentApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>@ViewBag.Title</title>
        <meta charset="utf-8" />
    </head>
    <body>
        @RenderBody()
    </body>
</html>

AppointmentApp/Views/SignUp/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
    <link href="../../../Content/main.css" rel="stylesheet" type="text/css" />
    <link href="../../../Content/fonts.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div id="black-header-wrapper">
        <div id="header" class="container">
            <div id="logo">
                <h1><a href="/">Central Perk</a></h1>
            </div>
            <div id="menu">
                <ul>
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Login/SignUp", "Index", "Login")</li>
                    <li>@Html.ActionLink("About Us", "Index", "AboutUs")</li>
                    <li>@Html.ActionLink("Contact Us", "Index", "Services")</li>
                </ul>
            </div>
        </div>
        <div id="banner" class="container">
            <h1 class="form-heading">login Form</h1>
            <div class="login-form">
                <div class="main-div">
                    <div class="panel">
                        <p>Please enter your email and password</p>
                    </div>
                    <form id="Login">
                        <div class="form-group">
                            <input type="email" class="form-control" id="inputEmail" placeholder="Email Address" />
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" id="inputPassword" placeholder="Password" />
                        </div>
                        <div class="form-group">
                            <input type="firstName" class="form-control" id="inputFirstName" placeholder="FirstName" />
                        </div>
                        <div class="form-group">
                            <input type="firstName" class="form-control" id="inputLastname" placeholder="LastName" />
                        </div>
                        <div class="forgot">
                            @Html.ActionLink("Already have account?", "Index", "SignUp")
                            <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>